package Strings;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;

/**
 * Created by brprashant on 1/10/17.
 */
public class StringSetFunctions {
    public static void main(String[] args){
        String[] setA = {"JANMXE","LIPNZS","PDXEGX","FGNNQJ","CFCZLC","STDZEB","XSFPFJ","TZKCTC","LSNYOI","TUGGZE","ETNSFV","EENZLY","SBNOCK","AQPLNW","CCBNFA","AVHOBU","LDFCKC","JZSRPI","EOYNRC","NFDLEO","NYMVVE","JCVKFP","PLJBBG","EGAWAI","PEAVEN","TLWYQA","ABQKFL","FINGXH","PLJEUX","PIRZXG","KPLBXJ","NFHZRW","HNJRLF","ICUOJU","NFIRFX","OQBPTN","FKXXSZ","BLCFHZ","SFEHUL","PVWGSP","XAAHOB","ZTVUDA","EDTWGA","BZGOWA","MLARRJ","NEUTRN","GORGFA","KHLMNR","QEPOAL","CUXWDI","VXEGXJ","AMWTVE","VLIVAB","UXHVZA","GSPAMP","TPBYFY","TCNYOK","HDPYYW","HENOGL","CXMGKV","HEGFHU","JTMHRJ","FFQCTV","EABJUT","HWZRXS","DHINPS","ZNDPBM","GOPGPB","KURXYZ","CIBNJC","HRIJWK","SVVMBE","NNARAV","FIKPTY","SKQQMA","EFPUPV","UWVNOV","UCHEUO","YCAOQK","DOOZGG","KKQZIB","GPWSDT","GPWSDT","GELXFL","RJEXRA","UCGOTC","XQOIJL","QWXPKC","FUVASP","MJVMSR","KIOCTU","RLWSWE","CHJTQG","BDNEEK","LLXAGN","QINBXQ","GBECVB","YYBOUI","LRTXRZ","XWGXTI","TLTKLU","HSWTGD","NACZPR","HOWXDT","AFZPXI","CCUUQT","KZKYBJ","MHVTZS","OLUTJU","AVTHXQ","SKCFSU","YWNLNA","VRWFCE","ZAVPZP","LTPBRJ","GKNWSN","VWMUYJ","JEOLWD","QSVTEB","TNPOXU","OHLQFI","YUCYHF","FQJPMW","UACWLY","KZSRLP","ZPNJKO","RETUMI","XBPRXI","QDBBJZ","HSLLIW","GSWPMR","DJXOAD","XSCUOS","UQXUQS","IHFLKD","XBXVED","PGJCUW","XUKLMU","FYSRTP","ZSIZUH","QQDEFF","SFXAIT","LJHCJU","MABQEI","NVTOYP","CHJZQF","AAOYYA","NIBFWC","UGQDTG","OTPZUN","IMFUAE","AAUUQN","KAMWFI","SCLEKQ","KYWRSY","QFPKQY","UGXCNH","ZHJPHQ","QBMQDQ","VKKIFH","GADVAO","IPCGJI","DSAVAL","GXYGHD","LQFQUT","EHZSFG","HIOFZP","CWZASP","ZHQIJY","OOBMRK","OUKMMB","XXUEMC","ZNHTNM","USYSHL","UAYVCZ","QTHKLH","NNSDWQ","HULKYM","YLFYNK","LLLMHK","QIFJIO","ALSYYU","MCDUUL","PATMNL","XRXVBK","JDYHPH","IXAQTH","MWZGYF","OGACCN","KNCMRH","EZXYHB","LNZEUJ","HATVYS","ADLDJL","FLRMRC","SJBBFL","TXLPVV","QFJDCI","GOTFAS","IWNNNO","PDAAOP","LRPCBG","LCPVZN","YYHEBK","TMWPDD","JFLMXF","GAXNJP","IABSAO","UPIOBK","IRAACL","OEZXPS","EBSSYU","YWRDRX","PEVJEZ","YRAVIV","DXBFZG","MPFOHR","OMSEYD","RVTHXB","RQOTNL","SDAFND","ZRNMEQ","LBYOSM","GLUBFB","KYUOMN","VANAUC","DBMLDO","HHAFTG","MNTURQ","UPZRUG","QPKYXP","YUAEKV","AFQOSO","TGEJAC","VJJEVH","HKAWIG","PEISQS","QPMHCD","CYCQNL","FQTSSY","AYPMSL","VYOOCY","VZUCIY","CPYCTO","VDMVNM","NNMHEY","ZXOIGR","PKCQYE","YJKWOU"};
        System.out.println("A list size :" + setA.length);
        String[] setB = {	"TNPOXU","EENZLY","IHFLKD","NIBFWC","TXLPVV","FFQCTV","DBMLDO","XXUEMC","GBECVB","UXHVZA","OOBMRK","DSAVAL","RETUMI","OUKMMB","BDNEEK","SVVMBE","HATVYS","DHINPS","AFZPXI","VANAUC","AYPMSL","HNJRLF","GSWPMR","KPLBXJ","ZAVPZP","RLWSWE","BLCFHZ","XUKLMU","EZXYHB"};
        System.out.println("B list size :" + setB.length);
        ArrayList<String> setAList = new ArrayList<>();
        Collections.addAll(setAList, setA);
        for(String str : setB){
            while(setAList.contains(str)){
                setAList.remove(str);
            }
        }
        System.out.println("total result " + setAList.size());

    }
}
